# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
   config.vm.box = "ferventcoder/win7pro-x64-nocm-lite"
#  config.vm.box = "opendds"
#  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
 config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  config.vm.communicator="winrm"
#  config.vm.provision "shell", path: "install_opendds.bat"
config.vm.provision "shell", path: "stage.bat"
  config.vm.provider "virtualbox" do |v|
    v.name = "open_dds"
  end
end
